# docker-compose.yml
version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8089:80"
    env_file:
      - ./.env
    environment:
      MESSAGE: "Hello from Docker Swarm!"
    deploy:
      replicas: 1
